### PR TITLE
re efactor

### PR DESCRIPTION
**Pull request by sample-text-here**
nooo oo o you cant refactor literally everything in someont elses repo

**me**: haha js go brrr

### CODE REVIEW

**Comment by sample-text-here** [comment]
ok everything is broken

it says that `blocks().each` is not a function, but the original code works and uses it?

**Comment by sample-text-here** [comment]
even stranger, everything works when copied into console but not as a mod...?

**Comment by QmelZ** [comment]
no no no dont

**Comment by sample-text-here** [comment]
o ok

**Pull request closed without merging**
